Revert "AudioService: permission for volume adjustment to lowest values"
This reverts commit ca6a2fb0fac91f3edebead11cac70a40c551f538.

Reason for revert: break git_master of errorprone target

out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/errorprone/srcjars/frameworks/base/services/core/java/com/android/server/audio/AudioService.java:4710: error: [EqualsNaN] == NaN always returns false; use the isNaN methods instead
                MIN_STREAM_VOLUME[AudioSystem.STREAM_ALARM], deviceForAlarm) == Float.NaN) {
                                                                             ^
    (see https://errorprone.info/bugpattern/EqualsNaN)
  Did you mean 'if (Float.isNaN(AudioSystem.getStreamVolumeDB(AudioSystem.STREAM_ALARM,'?

Bug: 157108450

Change-Id: Icf74dcbefccee6138473101e8dc23fba35faf5ce