Fix MmtpRecordEvent and TsRecordEvent NoSuchMethodError crash in jni
Due to Tuner 1.1 extension, these two java classes should have had
more parameters in their class descriptors.

Test: atest android.media.tv.tuner.cts
Bug: 181152149
Change-Id: I6c8e5996a449b272e1b712135f28bee428d776a8