Move Theme::Entry definition to top of file
It needs to be at least above this line:

    theme->entries_.reserve(kInitialReserveSize);

Otherwise, after upgrading libc++, the compiler fails with errors about
an incomplete type, e.g.:

include/c++/v1/vector:839:62: error: arithmetic on a pointer to an incomplete type 'android::Theme::Entry'
include/c++/v1/__memory/uninitialized_algorithms.h:609:5: error: cannot increment value of type 'std::reverse_iterator<android::Theme::Entry *>'

Bug: b/175635923
Test: treehugger
Change-Id: I6c231184c3a4c0e67dd29d43560b0c28778883db